default['redisio']['job_control'] = 'upstart'
default['redisio']['servers']['name'] = 'master'
default['redisio']['servers']['port'] = '6379'
default['redisio']['base_piddir'] = '/var/run/redis/'
default['redis']['version'] = '3.2.4'
default['roshi']['version'] = '1'
